package it.crystalnest.prometheus.mixin;

import it.crystalnest.prometheus.api.Fire;
import it.crystalnest.prometheus.api.FireManager;
import it.crystalnest.prometheus.api.type.FireTypeChanger;
import net.minecraft.core.Direction;
import net.minecraft.core.Position;
import net.minecraft.world.entity.projectile.Projectile;
import net.minecraft.world.item.FireChargeItem;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Injects into {@link FireChargeItem} to alter Fire behavior for consistency.
 */
@Mixin(FireChargeItem.class)
public abstract class FireChargeItemMixin {
  /**
   * Injects into the method {@link FireChargeItem#asProjectile(Level, Position, ItemStack, Direction)} at return.<br>
   * Sets the correct fire type to the entity generated by shooting a {@link FireChargeItem}.
   *
   * @param cir {@link CallbackInfoReturnable}.
   */
  @Inject(method = "asProjectile", at = @At(value = "RETURN"))
  private void onAsProjectile(CallbackInfoReturnable<Projectile> cir) {
    ((FireTypeChanger) cir.getReturnValue()).setFireType(FireManager.getFireType(Fire.Component.FIRE_CHARGE_ITEM, (FireChargeItem) (Object) this));
  }
}
